CREATE TABLE IF NOT EXISTS `CompletionRecord` (
  `partition_dtm` datetime(6) NOT NULL,
  `CompletionRecordId` char(36) NOT NULL,
  `LearnerId` char(36) COLLATE utf8_unicode_ci NOT NULL,
  `CompletionDate` datetime(6) NOT NULL,
  `LearningAsset` varchar(200) NOT NULL,
  `ActivityID` varchar(200) NOT NULL,
  `ActivityName` varchar(200) NOT NULL,
  `ActivityType` smallint NOT NULL,
  `ProviderName` varchar(200) NOT NULL,
  `LearningStructure` smallint NOT NULL,
  `AQFLevel` smallint NOT NULL,
  `DeliveryType` smallint NOT NULL,
  `LearningType` smallint NOT NULL,
  `TopicId` text NOT NULL,
  `TotalMinutes` int(11) NOT NULL,
  `TotalHours` decimal NOT NULL,
  `TotalPoints` decimal NOT NULL,
  `Accreditation` text NOT NULL,
  PRIMARY KEY (`CompletionRecordId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
